### PR TITLE
fix: don't cache icon background

### LINKED ISSUE #425: Scripts with same id overwrite background
I have a bunch of tiles that call the same script, as follows:

               {
                  position: [0, 0],
                  type: TYPES.SCRIPT,
                  id: 'script.sonos_wallpanel',
                  bg: 'images/radiostations/radioparadise.png',
                  variables: {source: 'radioparadise'},
               },
               {
                  position: [1, 0],
                  type: TYPES.SCRIPT,
                  id: 'script.sonos_wallpanel',
                  bg: 'images/radiostations/demoscene.png',
                  variables: {source: 'demoscene'},
               },

Clicking these launch the script with different variable values, this works as expected. However, both tiles show the same background image radioparadise.png. When changing the id of the second tile, the background is then respected (demoscene.png is shown for the second tile).

### PR DESCRIPTION
**Pull request by akloeckner**
fixes #425

### CODE REVIEW

File: scripts/controllers/main.js [hunk 1]
```diff
@@ -440,34 +440,17 @@ App.controller('Main', function ($scope, $timeout, $location, Api) {
...
-      return obj.bgStyles;
+      return cacheInItem(item, 'bgStyles', () => {
+         const bg = getItemFieldValue('bg', item, entity);
+         const bgSuffix = getItemFieldValue('bgSuffix', item, entity);
+         const opacity = getItemFieldValue('bgOpacity', item, entity);
+
+         return {
+            opacity: opacity || null,
+            backgroundImage: bg ? 'url(' + bg + ')'
+               : bgSuffix ? 'url(' + toAbsoluteServerURL(bgSuffix) + ')' : null,
```
Comment (rchl) [inline scripts/controllers/main.js:451]: It's safer to keep the double quote. Otherwise, a `(` in the path (for example) would break parsing.

While at it, you can also switch to template literal:
```
`url("${toAbsoluteServerURL(bgSuffix)}")`
```

**Comment by rchl** [comment]
Actually, I've just realized some potential issues with it. The background of the entity can change dynamically - for example, media player tiles' background should change on the next song. I think this will break that.

File: scripts/controllers/main.js (hunk 1 above)
Comment (akloeckner) [reply scripts/controllers/main.js]: done

**Comment by akloeckner** [comment]
That's true. But it was broken before then already. Nice thing about the new implementation with `cacheInItem` is that we can simply remove that function call and be good... ;-) 

Shall we? I don't know the inner workings of AngularJS well enough. 

We could also add a dummy cache, which is updated constantly, but will prevent any watchers from executing. Or do we need the watchers to execute in order to update the background? Seems a bit overdone to me, anyways.

**Comment by rchl** [comment]
It wasn't broken before. Probably because the `entity` was recreated every time there was an update so caching didn't really do much in practice.

If we return a new object every time this function is called then angular will notify all watchers, even the values didn't really change. And that means that the DOM style property will be updated every time. I guess that was happening before anyway and the browser will actually optimize it so that nothing really happens. So while ideally notifying listeners would be preferred, I'm fine with just returning a new object everytime.
