### PR TITLE
fix(popup): popup timeout now accessible to user on $scope

### LINKED ISSUE #496: Popup Timed or Trigger Closure
Is it possble to implement or advise how to use the following features?
- popup card auto close after a certain duration (either since open or since last action?)
- add logic to button on a popup card to close, after performing action.

For example, I have a popup card for music selection, and I would like the popup card to close after you select an option. Right now it will just remain on the popup until you close it or click outside the popup.

### PR DESCRIPTION
**Pull request by akloeckner**
Fixes #496 
See also #509 

This allows users to use the popup timeout feature themselves as outlined in #496 .

### CODE REVIEW

File: scripts/controllers/main.js [hunk 1]
```diff
@@ -1407,8 +1407,8 @@ App.controller('Main', function ($scope, $timeout, $location, Api) {
    };
 
    $scope.closePopup = function () {
-      if (popupTimeout) {
-         clearTimeout(popupTimeout);
+      if ($scope.popupTimeout) {
+         clearTimeout($scope.popupTimeout);
       }
```
Comment (rchl) [inline scripts/controllers/main.js:1412]: Set `$scope.popupTimeout` to `null` after clearing the timeout. Also in `openPopup`.

**Review by rchl — APPROVED** [review]
